Repository Codo-Baggins/covid_comparisons, pull requests merged in 2021-01, with the labels that each got.

#14 Feature/app setup
  .eslintcache
  package-lock.json
  package.json
  src/App.tsx
  src/App/App.scss
  src/App/App.test.tsx
  src/App/App.tsx
  src/ComparisonContainer/ComparisonContainer.scss
  src/ComparisonContainer/ComparisonContainer.tsx
  src/ComparisonDetails/ComparisonDetails.scss
  src/ComparisonDetails/ComparisonDetails.tsx
  src/Stat/Stat.scss
  src/Stat/Stat.tsx
  src/USAState/USAState.scss
  src/USAState/USAState.tsx
  src/index.tsx
Labels: component, enhancement, feature

#17 Feature/api calls
  .eslintcache
  package-lock.json
  package.json
  src/App/App.tsx
  src/Stat/Stat.tsx
  src/USAState/USAState.tsx
  src/apiCalls.tsx
Labels: apiCalls, component, enhancement, feature

#18 Feature/initial styles
  .eslintcache
  public/index.html
  src/App/App.scss
  src/App/App.tsx
  src/ComparisonContainer/ComparisonContainer.scss
  src/ComparisonContainer/ComparisonContainer.tsx
  src/Stat/Stat.scss
  src/Stat/Stat.tsx
  src/USAState/USAState.scss
  src/USAState/USAState.tsx
Labels: css, enhancement

#19 Testing/initial tests
  .eslintcache
  package-lock.json
  package.json
  src/App/App.test.tsx
  src/App/App.tsx
  src/ComparisonContainer/ComparisonContainer.test.tsx
  src/ComparisonContainer/ComparisonContainer.tsx
  src/Stat/Stat.test.tsx
  src/Stat/Stat.tsx
  src/USAState/USAState.test.tsx
  src/USAState/USAState.tsx
  src/index.tsx
  src/logo.svg
  src/reportWebVitals.ts
  src/sampleData.tsx
  src/setupTests.ts
Labels: fix, testing

#22 Feature/comparison details
  .eslintcache
  package-lock.json
  package.json
  src/App/App.scss
  src/App/App.tsx
  src/ComparisonContainer/ComparisonContainer.scss
  src/ComparisonContainer/ComparisonContainer.tsx
  src/ComparisonDetails/ComparisonDetails.tsx
  src/comparisonData.tsx
  src/index.tsx
Labels: enhancement, feature, router

#27 Styles/comparisons container and details
  .eslintcache
  src/App/App.tsx
  src/ComparisonContainer/ComparisonContainer.scss
  src/ComparisonContainer/ComparisonContainer.tsx
  src/ComparisonDetails/ComparisonDetails.tsx
  src/comparisonData.tsx
Labels: enhancement, fix, router

#30 Testing/integration testing
  .eslintcache
  package-lock.json
  package.json
  src/App/App.test.tsx
  src/App/App.tsx
  src/ComparisonContainer/ComparisonContainer.test.tsx
  src/ComparisonContainer/ComparisonContainer.tsx
  src/ComparisonDetails/ComparisonDetails.tsx
  src/sampleData.tsx
Labels: testing

#31 Styles/comparisons container and details
  .eslintcache
  src/App/App.scss
  src/App/App.tsx
  src/ComparisonContainer/ComparisonContainer.scss
  src/ComparisonContainer/ComparisonContainer.tsx
  src/ComparisonDetails/ComparisonDetails.scss
  src/ComparisonDetails/ComparisonDetails.tsx
  src/Stat/Stat.scss
  src/USAState/USAState.scss
Labels: css, enhancement, refactor, responsiveness

#33 Feature/comparison details logic
  .eslintcache
  src/App/App.tsx
  src/ComparisonCard/ComparisonCard.tsx
  src/ComparisonDetails/ComparisonDetails.scss
  src/ComparisonDetails/ComparisonDetails.tsx
  src/comparisonData.tsx
Labels: component, enhancement, feature

#34 Refactor/utilities
  .eslintcache
  src/App/App.test.tsx
  src/App/App.tsx
  src/sampleData.tsx
  src/utilities/utilities.test.tsx
  src/utilities/utilities.tsx
Labels: refactor

#40 Testing/refactor testing
  .eslintcache
  src/App/App.test.tsx
  src/App/App.tsx
  src/ComparisonCard/ComparisonCard.test.tsx
  src/ComparisonContainer/ComparisonContainer.test.tsx
  src/sampleData.tsx
Labels: testing

#41 Feature/comparison card styles
  .eslintcache
  src/ComparisonCard/ComparisonCard.scss
  src/ComparisonCard/ComparisonCard.tsx
  src/ComparisonDetails/ComparisonDetails.scss
  src/ComparisonDetails/ComparisonDetails.tsx
  src/Stat/Stat.scss
  src/Stat/Stat.tsx
Labels: component, css, enhancement

#42 Cleanup
  .eslintcache
  src/App/App.test.tsx
  src/ComparisonDetails/ComparisonDetails.tsx
  src/sampleData.tsx
Labels: testing
